const CHECK_TYPES = {
  USER_MFA_ENABLED: "USER_MFA_ENABLED",
  TABLE_RLS_ENABLED: "TABLE_RLS_ENABLED",
  PROJECT_PITR_ENABLED: "PROJECT_PITR_ENABLED",
};

const CHECK_TYPES_DISPLAY = {
  [CHECK_TYPES.USER_MFA_ENABLED]: "User MFA Enabled",
  [CHECK_TYPES.TABLE_RLS_ENABLED]: "Table Row Level Security Enabled",
  [CHECK_TYPES.PROJECT_PITR_ENABLED]: "Project PITR Enabled",
};

export { CHECK_TYPES, CHECK_TYPES_DISPLAY };
